Exit `happo compare` with a status of 3 if there is a diff
So that we can conditionally check this in the happo-ci script. 113 was
chosen because it's in the recommended user-defined range on
http://tldp.org/LDP/abs/html/exitcodes.html#EXITCODESREF

diff --git a/bin/happo-ci b/bin/happo-ci
--- a/bin/happo-ci
+++ b/bin/happo-ci
@@ -53,14 +53,23 @@ run-happo "$CURRENT_SHA"
 # Compare reports from the two SHAs.
 COMMIT_SUBJECT="$(git show -s --format=%s)"
 COMMIT_AUTHOR="$(git show -s --format=%ae)"
+
+# `happo compare` exits with an exit code of 3 if there is a diff. To work with
+# the exit status, we need to temporarily turn off the fail-on-error behavior.
+set +e
 SUMMARY=$(${NPM_CLIENT} run --silent \
   happo compare "$PREVIOUS_SHA" "$CURRENT_SHA" \
   --link "$CHANGE_URL" \
   --message "$COMMIT_SUBJECT" \
-  --author "$COMMIT_AUTHOR" || true)
+  --author "$COMMIT_AUTHOR")
+EXIT_CODE=$?
+set -e
 
-if [ -z "$SUMMARY" ]; then
-  echo "No diffs"
-else
-  echo "$SUMMARY"
+echo "$SUMMARY"
+
+if [ "$EXIT_CODE" = "113" ]; then
+  # There is a diff. We don't want to fail the script in this case.
+  exit 0
 fi
+
+exit $EXIT_CODE
